import { SearchMappingRequest, SearchMappingResponse } from '../dto/searchMapping.dto';
import { generateSearchSignature } from '../utils/search.signature.util';
import { findSearchMapping, saveSearchMapping } from '../repository/searchMapping.repository';
import { callLLMForSearchMapping } from './searchLlm.service';
import { getUserSearchPreferences, transformSearchData } from '../utils/search.transform.util';

/**
 * Core business logic for the Search Mapping API.
 *
 * Flow:
 *  1. Generate a deterministic form signature from provider + vertical + fieldId + type + label + section
 *     (fieldId is deterministically generated by extension — source of truth for field identity)
 *  2. Check DB — if mapping cached, return immediately (no LLM call)
 *  3. Cache miss — call LLM, sanitize output, persist to DB
 *  4. Fetch user search preferences (currently mock; switches to real API transparently)
 *  5. Transform mapping → concrete autofill values using preferences[vertical]
 *  6. Return { provider, vertical, mapping, values }
 *
 * Extensibility:
 *  - New verticals require no changes here — they are handled by the prompt
 *    builder (VERTICAL_KEYS map) and the transform util (MOCK_SEARCH_PREFERENCES).
 *  - Swapping the preferences data source only requires updating
 *    `getUserSearchPreferences` in search.transform.util.ts.
 */
export async function resolveSearchMapping(
  req: SearchMappingRequest,
): Promise<SearchMappingResponse> {
  const { provider, vertical, fields } = req;

  // ── Step 1: Deterministic signature ────────────────────────────────────────
  const formSignature = generateSearchSignature(provider, vertical, fields);
  console.log(
    `[SearchMapping] provider=${provider} vertical=${vertical} signature=${formSignature.slice(0, 16)}...`,
  );

  // ── Step 2: Cache lookup ────────────────────────────────────────────────────
  const cached = await findSearchMapping(provider, vertical, formSignature);
  if (cached) {
    console.log(`[SearchMapping] Cache hit — returning stored mapping`);

    // Re-scope the cached record to only the fieldIds in this request.
    // (Defensive: different page-load fieldIds should still resolve correctly.)
    const mapping: Record<string, string | null> = {};
    for (const field of fields) {
      mapping[field.fieldId] = cached[field.fieldId] ?? null;
    }

    const preferences = await getUserSearchPreferences();
    const values      = transformSearchData(mapping, preferences, vertical);

    return { provider, vertical, mapping, values };
  }

  // ── Step 3: Cache miss — call LLM ──────────────────────────────────────────
  console.log(`[SearchMapping] Cache miss — calling LLM for ${fields.length} fields (${vertical})`);
  const rawMapping = await callLLMForSearchMapping(provider, vertical, fields);

  // Guarantee only requested fieldIds are in the mapping (LLM should comply,
  // but this is a hard safety net)
  const mapping: Record<string, string | null> = {};
  for (const field of fields) {
    mapping[field.fieldId] = rawMapping[field.fieldId] ?? null;
  }

  // ── Step 4: Persist to DB ──────────────────────────────────────────────────
  await saveSearchMapping(provider, vertical, formSignature, mapping);
  console.log(`[SearchMapping] Stored mapping for ${provider}/${vertical}`);

  // ── Step 5: Fetch preferences + transform ─────────────────────────────────
  const preferences = await getUserSearchPreferences();
  const values      = transformSearchData(mapping, preferences, vertical);

  // ── Step 6: Return ─────────────────────────────────────────────────────────
  return { provider, vertical, mapping, values };
}
